# CMake generated Testfile for 
# Source directory: /home/eric/Documents/recolor-tm7-e
# Build directory: /home/eric/Documents/recolor-tm7-e
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_game_new "test_game_ejin" "new")
set_tests_properties(test_game_new PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;37;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_new_empty "test_game_ejin" "newempty")
set_tests_properties(test_game_new_empty PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;38;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_set_cell "test_game_ejin" "setcell")
set_tests_properties(test_game_set_cell PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;39;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_newext "test_game_ejin" "newext")
set_tests_properties(test_newext PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;40;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_set_max_moves "test_game_zboumedris" "setmax")
set_tests_properties(test_game_set_max_moves PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;44;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_nb_moves_max "test_game_zboumedris" "nbmovesmax")
set_tests_properties(test_game_nb_moves_max PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;45;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_cell_current_color "test_game_zboumedris" "cellcolor")
set_tests_properties(test_game_cell_current_color PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;46;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_height "test_game_zboumedris" "height")
set_tests_properties(test_game_height PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;47;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_restart "test_game_lalanoix" "restart")
set_tests_properties(test_game_restart PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;51;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_is_over "test_game_lalanoix" "isover")
set_tests_properties(test_game_is_over PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;52;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_game_delete "test_game_lalanoix" "delete")
set_tests_properties(test_game_delete PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;53;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_iswrapping "test_game_lalanoix" "iswrapping")
set_tests_properties(test_iswrapping PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;54;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_width "test_game_lalanoix" "width")
set_tests_properties(test_width PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;55;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_gameload "test_game_lalanoix" "load")
set_tests_properties(test_gameload PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;56;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_gamesave "test_game_lalanoix" "save")
set_tests_properties(test_gamesave PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;57;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_nbmovescur "test_game_anouamani" "nbmovescur")
set_tests_properties(test_nbmovescur PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;61;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_playonemouve "test_game_anouamani" "playonemove")
set_tests_properties(test_playonemouve PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;62;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_copy "test_game_anouamani" "copy")
set_tests_properties(test_copy PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;63;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_emptyext "test_game_anouamani" "emptyext")
set_tests_properties(test_emptyext PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;64;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
add_test(test_gamedef "test_game_anouamani" "gamedef")
set_tests_properties(test_gamedef PROPERTIES  _BACKTRACE_TRIPLES "/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;65;add_test;/home/eric/Documents/recolor-tm7-e/CMakeLists.txt;0;")
