# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/177/bin/cmake

# The command to remove a file.
RM = /snap/cmake/177/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayoub/git/recolor_clone/recolor-tm7-e

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayoub/git/recolor_clone/recolor-tm7-e

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/177/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/148/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/snap/cmake/177/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayoub/git/recolor_clone/recolor-tm7-e/CMakeFiles /home/ayoub/git/recolor_clone/recolor-tm7-e/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayoub/git/recolor_clone/recolor-tm7-e/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named recolor_text

# Build rule for target.
recolor_text: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 recolor_text
.PHONY : recolor_text

# fast build rule for target.
recolor_text/fast:
	$(MAKE) -f CMakeFiles/recolor_text.dir/build.make CMakeFiles/recolor_text.dir/build
.PHONY : recolor_text/fast

#=============================================================================
# Target rules for targets named test_game_zboumedris

# Build rule for target.
test_game_zboumedris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_game_zboumedris
.PHONY : test_game_zboumedris

# fast build rule for target.
test_game_zboumedris/fast:
	$(MAKE) -f CMakeFiles/test_game_zboumedris.dir/build.make CMakeFiles/test_game_zboumedris.dir/build
.PHONY : test_game_zboumedris/fast

#=============================================================================
# Target rules for targets named test_game_ejin

# Build rule for target.
test_game_ejin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_game_ejin
.PHONY : test_game_ejin

# fast build rule for target.
test_game_ejin/fast:
	$(MAKE) -f CMakeFiles/test_game_ejin.dir/build.make CMakeFiles/test_game_ejin.dir/build
.PHONY : test_game_ejin/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named test_game_lalanoix

# Build rule for target.
test_game_lalanoix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_game_lalanoix
.PHONY : test_game_lalanoix

# fast build rule for target.
test_game_lalanoix/fast:
	$(MAKE) -f CMakeFiles/test_game_lalanoix.dir/build.make CMakeFiles/test_game_lalanoix.dir/build
.PHONY : test_game_lalanoix/fast

#=============================================================================
# Target rules for targets named test_game_anouamani

# Build rule for target.
test_game_anouamani: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_game_anouamani
.PHONY : test_game_anouamani

# fast build rule for target.
test_game_anouamani/fast:
	$(MAKE) -f CMakeFiles/test_game_anouamani.dir/build.make CMakeFiles/test_game_anouamani.dir/build
.PHONY : test_game_anouamani/fast

game.o: game.c.o

.PHONY : game.o

# target to build an object file
game.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game.c.o
.PHONY : game.c.o

game.i: game.c.i

.PHONY : game.i

# target to preprocess a source file
game.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game.c.i
.PHONY : game.c.i

game.s: game.c.s

.PHONY : game.s

# target to generate assembly for a file
game.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game.c.s
.PHONY : game.c.s

game_io.o: game_io.c.o

.PHONY : game_io.o

# target to build an object file
game_io.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game_io.c.o
.PHONY : game_io.c.o

game_io.i: game_io.c.i

.PHONY : game_io.i

# target to preprocess a source file
game_io.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game_io.c.i
.PHONY : game_io.c.i

game_io.s: game_io.c.s

.PHONY : game_io.s

# target to generate assembly for a file
game_io.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game_io.c.s
.PHONY : game_io.c.s

recolor_text.o: recolor_text.c.o

.PHONY : recolor_text.o

# target to build an object file
recolor_text.c.o:
	$(MAKE) -f CMakeFiles/recolor_text.dir/build.make CMakeFiles/recolor_text.dir/recolor_text.c.o
.PHONY : recolor_text.c.o

recolor_text.i: recolor_text.c.i

.PHONY : recolor_text.i

# target to preprocess a source file
recolor_text.c.i:
	$(MAKE) -f CMakeFiles/recolor_text.dir/build.make CMakeFiles/recolor_text.dir/recolor_text.c.i
.PHONY : recolor_text.c.i

recolor_text.s: recolor_text.c.s

.PHONY : recolor_text.s

# target to generate assembly for a file
recolor_text.c.s:
	$(MAKE) -f CMakeFiles/recolor_text.dir/build.make CMakeFiles/recolor_text.dir/recolor_text.c.s
.PHONY : recolor_text.c.s

test_game_anouamani.o: test_game_anouamani.c.o

.PHONY : test_game_anouamani.o

# target to build an object file
test_game_anouamani.c.o:
	$(MAKE) -f CMakeFiles/test_game_anouamani.dir/build.make CMakeFiles/test_game_anouamani.dir/test_game_anouamani.c.o
.PHONY : test_game_anouamani.c.o

test_game_anouamani.i: test_game_anouamani.c.i

.PHONY : test_game_anouamani.i

# target to preprocess a source file
test_game_anouamani.c.i:
	$(MAKE) -f CMakeFiles/test_game_anouamani.dir/build.make CMakeFiles/test_game_anouamani.dir/test_game_anouamani.c.i
.PHONY : test_game_anouamani.c.i

test_game_anouamani.s: test_game_anouamani.c.s

.PHONY : test_game_anouamani.s

# target to generate assembly for a file
test_game_anouamani.c.s:
	$(MAKE) -f CMakeFiles/test_game_anouamani.dir/build.make CMakeFiles/test_game_anouamani.dir/test_game_anouamani.c.s
.PHONY : test_game_anouamani.c.s

test_game_ejin.o: test_game_ejin.c.o

.PHONY : test_game_ejin.o

# target to build an object file
test_game_ejin.c.o:
	$(MAKE) -f CMakeFiles/test_game_ejin.dir/build.make CMakeFiles/test_game_ejin.dir/test_game_ejin.c.o
.PHONY : test_game_ejin.c.o

test_game_ejin.i: test_game_ejin.c.i

.PHONY : test_game_ejin.i

# target to preprocess a source file
test_game_ejin.c.i:
	$(MAKE) -f CMakeFiles/test_game_ejin.dir/build.make CMakeFiles/test_game_ejin.dir/test_game_ejin.c.i
.PHONY : test_game_ejin.c.i

test_game_ejin.s: test_game_ejin.c.s

.PHONY : test_game_ejin.s

# target to generate assembly for a file
test_game_ejin.c.s:
	$(MAKE) -f CMakeFiles/test_game_ejin.dir/build.make CMakeFiles/test_game_ejin.dir/test_game_ejin.c.s
.PHONY : test_game_ejin.c.s

test_game_lalanoix.o: test_game_lalanoix.c.o

.PHONY : test_game_lalanoix.o

# target to build an object file
test_game_lalanoix.c.o:
	$(MAKE) -f CMakeFiles/test_game_lalanoix.dir/build.make CMakeFiles/test_game_lalanoix.dir/test_game_lalanoix.c.o
.PHONY : test_game_lalanoix.c.o

test_game_lalanoix.i: test_game_lalanoix.c.i

.PHONY : test_game_lalanoix.i

# target to preprocess a source file
test_game_lalanoix.c.i:
	$(MAKE) -f CMakeFiles/test_game_lalanoix.dir/build.make CMakeFiles/test_game_lalanoix.dir/test_game_lalanoix.c.i
.PHONY : test_game_lalanoix.c.i

test_game_lalanoix.s: test_game_lalanoix.c.s

.PHONY : test_game_lalanoix.s

# target to generate assembly for a file
test_game_lalanoix.c.s:
	$(MAKE) -f CMakeFiles/test_game_lalanoix.dir/build.make CMakeFiles/test_game_lalanoix.dir/test_game_lalanoix.c.s
.PHONY : test_game_lalanoix.c.s

test_game_zboumedris.o: test_game_zboumedris.c.o

.PHONY : test_game_zboumedris.o

# target to build an object file
test_game_zboumedris.c.o:
	$(MAKE) -f CMakeFiles/test_game_zboumedris.dir/build.make CMakeFiles/test_game_zboumedris.dir/test_game_zboumedris.c.o
.PHONY : test_game_zboumedris.c.o

test_game_zboumedris.i: test_game_zboumedris.c.i

.PHONY : test_game_zboumedris.i

# target to preprocess a source file
test_game_zboumedris.c.i:
	$(MAKE) -f CMakeFiles/test_game_zboumedris.dir/build.make CMakeFiles/test_game_zboumedris.dir/test_game_zboumedris.c.i
.PHONY : test_game_zboumedris.c.i

test_game_zboumedris.s: test_game_zboumedris.c.s

.PHONY : test_game_zboumedris.s

# target to generate assembly for a file
test_game_zboumedris.c.s:
	$(MAKE) -f CMakeFiles/test_game_zboumedris.dir/build.make CMakeFiles/test_game_zboumedris.dir/test_game_zboumedris.c.s
.PHONY : test_game_zboumedris.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... recolor_text"
	@echo "... edit_cache"
	@echo "... test_game_zboumedris"
	@echo "... test_game_ejin"
	@echo "... game"
	@echo "... test_game_lalanoix"
	@echo "... test"
	@echo "... test_game_anouamani"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... game_io.o"
	@echo "... game_io.i"
	@echo "... game_io.s"
	@echo "... recolor_text.o"
	@echo "... recolor_text.i"
	@echo "... recolor_text.s"
	@echo "... test_game_anouamani.o"
	@echo "... test_game_anouamani.i"
	@echo "... test_game_anouamani.s"
	@echo "... test_game_ejin.o"
	@echo "... test_game_ejin.i"
	@echo "... test_game_ejin.s"
	@echo "... test_game_lalanoix.o"
	@echo "... test_game_lalanoix.i"
	@echo "... test_game_lalanoix.s"
	@echo "... test_game_zboumedris.o"
	@echo "... test_game_zboumedris.i"
	@echo "... test_game_zboumedris.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

